// Generated with gemini
export const areas = [
    'Alergología',
    'Análisis Clínicos',
    'Anatomía Patológica',
    'Atención al Paciente / Servicio de Información',
    'Bioquímica',
    'Box de Reanimación / Box de Críticos',
    'Cardiología',
    'Cirugía General y del Aparato Digestivo',
    'Dermatología',
    'Dirección de Enfermería',
    'Dirección de Gestión y Servicios Generales',
    'Dirección Financiera / Administrativa',
    'Dirección General / Gerencia',
    'Dirección Médica',
    'Dirección de Recursos Humanos',
    'Ecografía / Ultrasonido',
    'Endocrinología',
    'Endoscopia Digestiva',
    'Esterilización',
    'Farmacia Hospitalaria',
    'Gastroenterología',
    'Ginecología y Obstetricia',
    'Hematología',
    'Hematología (laboratorio)',
    'Higiene Hospitalaria / Limpieza',
    'Infectología',
    'Informática / Sistemas de la Información',
    'Inmunología',
    'Laboratorio Clínico',
    'Limpieza / Higiene Hospitalaria',
    'Logopedia',
    'Mamografía',
    'Mantenimiento',
    'Maternidad / Sala de Partos',
    'Medicina Interna',
    'Medicina Nuclear',
    'Microbiología',
    'Nefrología',
    'Neonatología / Unidad de Cuidados Intensivos Neonatales (UCIN)',
    'Neumología',
    'Neurología',
    'Nutrición y Dietética / Servicios de Alimentación',
    'Oftalmología',
    'Oncología Médica',
    'Otorrinolaringología (ORL)',
    'Pediatría',
    'Quirófano / Área Quirúrgica',
    'Radiodiagnóstico / Diagnóstico por Imagen',
    'Radiología Convencional (Rayos X)',
    'Radioterapia Oncológica',
    'Rehabilitación y Fisioterapia',
    'Resonancia Magnética (RM)',
    'Reumatología',
    'Sala de Observación de Urgencias',
    'Sala de Partos / Maternidad',
    'Sala de Reanimación / Unidad de Recuperación Postanestésica (URPA)',
    'Seguridad',
    'Servicios de Alimentación / Nutrición y Dietética',
    'Sistemas de la Información / Informática',
    'Terapia Intensiva / Unidad de Cuidados Intensivos (UCI)',
    'Terapia Ocupacional',
    'Tomografía Axial Computarizada (TAC o TC)',
    'Trabajo Social',
    'Traumatología y Ortopedia',
    'Unidad Coronaria',
    'Unidad de Cirugía Mayor Ambulatoria (UCMA)',
    'Unidad de Cuidados Intensivos (UCI)',
    'Unidad de Cuidados Intensivos Neonatales (UCIN)',
    'Unidad de Diálisis',
    'Unidad de Recuperación Postanestésica (URPA)',
    'Urgencias / Emergencias',
    'Urología',
];
