// Generated with gemini
export const hospitals = [
    'A.O. Fox Memorial Hospital',
    'Abrazo Central Campus',
    'Abrazo West Campus',
    'AcuteCare Health System',
    'Adirondack Medical Center',
    'Alamance Regional Medical Center',
    'Alaska Native Medical Center',
    'Albert B. Chandler Hospital',
    'Alegent Health Mercy Hospital',
    'Alice Hyde Medical Center',
    'Alice Peck Day Hospital',
    'Allegan General Hospital',
    'Allen Hospital',
    'Alpena Regional Medical Center',
    'Altru Hospital',
    'Alvin J. Siteman Cancer Center',
    'Anaheim General Hospital',
    'Anderson County Hospital',
    'Angel Medical Center',
    'Animas Surgical Hospital',
    'Annie Penn Hospital',
    'Anthony Medical Center',
    'Arbour Hospital',
    'Arizona Heart Institute',
    "Arkansas Children's Hospital",
    'Arkansas Methodist Hospital',
    'Arkansas Surgical Hospital',
    'Arnold Palmer Hospital for Children',
    'Arrowhead Hospital',
    'Arroyo Grande Community Hospital',
    'Ashley County Medical Center',
    'Aspen Valley Hospital',
    'Aspirus Ontonagon Hospital',
    'Assumption General Medical Center',
    'Athens-Limestone Hospital',
    'Atlantic Rehabilitation Institute',
    'AtlantiCare Regional Medical Center Mainland Division',
    'Aurora Community Hospital',
    'Avalon Municipal Hospital',
    'Avista Adventist Hospital',
    'Ayesha Hospital',
    'Bakersfield Memorial Hospital',
    'Baltimore VA Medical Center',
    'Baraga County Memorial Hospital',
    'Barnes-Jewish Hospital',
    'Barrow Regional Medical Center',
    'Bartlett Regional Hospital',
    'Barton Memorial Hospital',
    'Bastrop Rehabilitation Hospital',
    'Bath Va Medical Center',
    'Baxter Regional Medical Center',
    'Bay Medical Center',
    'Bayley Seton Hospital',
    'Bayonne Medical Center',
    'Bayshore Community Hospital',
    'Beacon Center',
    'Bear Lake Memorial Hospital',
    'Beaumon Hospital',
    'Beauregard Memorial Hospital',
    'Behavioral Health Center at Westchester Medical Center',
    'Bellevue Hospital Center',
    'Bellflower Medical Center',
    'Bergen Regional Medical Center',
    'Bert Fish Medical Center',
    'Beth Israel Deaconess Medical Center',
    'Bethesda Memorial Hospital',
    'Beverly Hospital',
    'Bibb Medical Center',
    'Bingham Memorial Hospital',
    'Birkeland Maternity Center',
    'Blackford Community Hospital',
    'Blake Medical Center',
    "Blank Children's Hospital",
    'Bloomington Meadows Hospital',
    'Bluegrass Community Hospital',
    "Blythedale Children's Hospital",
    'Boca Raton Regional Hospital',
    'Bon Secours St. Petersburg',
    'Bonner General Hospital',
    'Boone Hospital Center',
    'Borgess-Lee Memorial Hospital',
    'Boston Medical Center',
    'Brandon Regional Hospital',
    'Breckinridge Memorial Hospital',
    'Bridgeport Hospital',
    'Brighton Hospital',
    'Bronson Battle Creek',
    'Brookhaven Memorial Hospital Medical Center Inc',
    'Brooks County Hospital',
    'Brooks Rehabilitation',
    'Brookwood Medical Center',
    'Broward Health Medical Center',
    'Broward Health Weston',
    'Bryan Whitfield Memorial Hospital',
    'Buena Vista Regional Medical Center',
    'Buffalo Niagara Medical Campus',
    'Bullitt County Medical Center',
    'Burbank Community Hospital',
    'Byrd Regional Hospital',
    'California Hospital Medical Center',
    'Calvary Hospital',
    'Cameron Memorial Community Hospital',
    'Cancer Institute of Maui',
    'Candler Hospital',
    'Cape Canaveral Hospital',
    'Cape Fear Valley-Bladen County Hospital',
    'Capital District Psychiatric Center',
    'Capital Region Medical Center',
    "Cardinal Glennon Children's Hospital",
    'CareLink of Jackson',
    'Caro Center',
    'CarolinaEast Medical Center',
    'Carolinas ContinueCARE Hospital at Pineville',
    'Carolinas Medical Center/Center for Mental Health',
    'Carolinas Rehabilitation Mt. Holly',
    'CaroMont Regional Medical Center',
    "Carondelet St. Joseph's Hospital",
    'Carson City Hospital',
    'Cass Medical Center',
    'Castle Medical Center',
    'Catholic Medical Center',
    'Cayuga Medical Center at Ithaca',
    'Cedars Medical Center',
    'CenterPointe Hospital',
    'Central Alabama Veterans Health Care System East Campus',
    'Central Florida Regional Hospital',
    'Central Kansas Medical Center',
    'Central New York Psychiatric Center',
    'Central State Hospital',
    'Central Valley General Hospital',
    'Century City Hospital',
    'Chapman Medical Center',
    'Charlevoix Area Hospital',
    'Chatuge Regional Hospital',
    'Chelsea Community Hospital',
    'Cherokee Regional Medical Center',
    'Chestatee Regional Hospital',
    "Children's Healthcare of Atlanta at Hughes Spalding",
    "Children's Hospital and Health Center",
    "Children's Hospital Colorado",
    "Children's Hospital Los Angeles",
    "Children's Hospital of Buffalo",
    "Children's Hospital of Georgia",
    "Children's Hospital of New Orleans",
    "Children's Mercy Northland",
    "Children's of Alabama Russell Campus",
    'Chilton Memorial Hospital',
    'Choctaw General Hospital',
    'Christ Hospital',
    'Christian Hospital',
    'Christus Schumpert Hospital',
    'Christus St. Patrick Hospital',
    'Citizens Medical Center',
    'Citrus Memorial Hospital',
    'City of Hope National Medical Center',
    'Clara Maass Medical Center',
    'Clark Regional Medical Center',
    'Cleveland Clinic Hospital',
    'Clifton-Fine Hospital',
    'Clinton County Hospital',
    'Coalinga Regional Medical Center',
    'Coast Plaza Hospital',
    'Cobre Valley Community Hospital',
    'Coffey County Hospital',
    'Coler-Goldwater Specialty Hospital',
    'Coliseum Northside Hospital',
    "Colmery-O'Neil VA Medical Center",
    'Colorado Canyons Hospital and Medical Center',
    'Colorado Mental Health Institute at Pueblo',
    'Colorado River Medical Center',
    'Columbia Regional Hospital',
    'Comanche County Hospital',
    'Community General Hospital',
    'Community HealthCare System',
    'Community Hospital at Dobbs Ferry',
    'Community Hospital North',
    'Community Hospital of Bremen',
    'Community Hospital of Los Gatos',
    'Community Hospital of the Monterey Peninsula',
    'Community Medical Center of Izard County',
    'Community Memorial Hospital',
    'Community Mental Health Center',
    'Comprehensive Health of Planned Parenthood of Kansas and Mid-Missouri',
    'Conejos County Hospital',
    "Connecticut Children's Medical Center",
    'Connecticut Valley Hospital',
    'Conway Regional Health System',
    'Cooper University Hospital',
    'Coosa Valley Medical Center',
    'Coral Gables Hospital',
    'Cordova Community Medical Center',
    'Corning Hospital',
    'Corona Regional Medical Center',
    "Cottage Children's Hospital",
    'County Hospital',
    'Cox North',
    'Cox Walnut Lawn',
    'Craig Hospital',
    'Crawford County Hospital District No.1',
    'Crenshaw Community Hospital',
    'Crisp Regional Hospital',
    'Crittenden Regional Hospital',
    'Crittenton Hospital Medical Center',
    'Crotched Mountain Rehabilitation Center',
    'Cuba Memorial Hospital',
    'Cumberland County Hospital',
    'Cushing Memorial Hospital',
    'D.W. McMillan Memorial Hospital',
    'Dallas County Hospital',
    'Dana-Farber Cancer Institute',
    'Dauterive Hospital',
    'Day Kimball Hospital',
    'De Queen Medical Center',
    'Deaconess Gateway Hospital',
    'Deaconess Incarnate Word Health System',
];
